import {Geist, Geist_Mono} from 'next/font/google'
import './globals.css'
import Header from '../components/Header.jsx'
import RightSide from '../components/RightSide'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
    <body
      className="max-w-[1240px] mx-auto px-5 py-5 flex gap-5"
    >
    <Header />
    {children}
    <RightSide />
    </body>
    </html>
  )
}
